"""empty message

Revision ID: 74692561c4af
Revises: 51291d734598
Create Date: 2020-04-17 20:52:01.799332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74692561c4af'
down_revision = '51291d734598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
